services:
  rl_backend:
    container_name:
      rl_backend
    env_file:
      - .env
    build:
      context: .
      dockerfile:
        core/Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./models:/app/models
      - ./profiling:/app/profiling
    stdin_open:
      true
    tty:
      true
    command: ["train", "-n", "7", "-m", "100", "--no-webhook"]

  frontend:
    container_name:
      frontend
    build:
      context: frontend
      dockerfile:
        frontend/Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - rl_backend
