ARG BASE_IMAGE="pytorch/pytorch"
FROM $BASE_IMAGE
WORKDIR /usr/src/app/

RUN apt-get update && apt-get install -y curl
COPY requirements.txt ./
RUN python -m pip install -r requirements.txt

COPY *.py ./
COPY env ./env
COPY config.json ./
ENTRYPOINT ["python", "main.py", "online"]