services:
  rl_backend:
    container_name:
      rl_backend
    build:
      context: .
      dockerfile:
        Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./models:/app/models
    env_file:
      - .env

  frontend:
    container_name:
      frontend
    build:
      context: ./frontend
      dockerfile:
        Dockerfile
    ports:
      - 3000:3000

    